coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
ignore:
  - go.mod
  - go.sum
  - docs/**
  - hack/**
  - scripts/**
  - templates/**
  - test/e2e/**
  - tilt_modules/**
  - "*.yaml"
  - "*.md"
  - "*.json"
  - Makefile
  - "*.mk"
  - Dockerfile
  - "*.toml"
  - OWNERS*
  - PROJECT
  - Tiltfile
